using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AIRadius : MonoBehaviour
{

    private GameObject playerTarget;

    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.CompareTag("Player"))
        {
            playerTarget = collision.gameObject;
        }
    }

    private void OnTriggerStay2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            playerTarget = collision.gameObject;
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            playerTarget = null;
        }
    }


    public GameObject GetTarget()
    {
        return playerTarget;
    }
}
